Verbose: false
Seconds-Delay: 1
Check-for-Updates: true
Give-New-Books-On-Join: true
Display-Messages: true
Block-Villager-Book-Trading: true
Give-Books-Every-Join: false
Keep-Books-On-Death: false
Language: EN