author: mstiles92
description: Distribute rule books, getting started guides, etc to players in the form of written books.
name: BookRules
main: com.mstiles92.plugins.bookrules.BookRules
version: '${project.version}'
startup: postworld
permissions:
  bookrules.*:
    description: Allows access to all commands.
    children:
      bookrules.info: true
      bookrules.reload: true
      bookrules.receivealerts: true
      bookrules.get: true
      bookrules.give: true
      bookrules.add: true
      bookrules.delete: true
      bookrules.edit: true
      bookrules.list: true
      bookrules.setauthor: true
      bookrules.settitle: true
      bookrules.unsign: true
  bookrules.info:
    default: true
    description: Show the current plugin information.
  bookrules.reload:
    default: op
    description: Reload the config files and books.
  bookrules.receivealerts:
    default: op
    description: Receive alerts when there is an update to the plugin.
  bookrules.get:
    default: true
    description: Allow players to receive books.
  bookrules.give:
    default: op
    description: Allow players to give books to other players.
  bookrules.add:
    default: op
    description: Allow players to add books to the plugin.
  bookrules.delete:
    default: op
    description: Allow players to delete books from the plugin.
  bookrules.update:
    default: op
    description: Allow players to update books stored by the plugin.
  bookrules.edit.*:
    description: Allow access to all edit commands.
    children:
      bookrules.edit.book: true
      bookrules.edit.group: true
  bookrules.edit.book:
    default: op
    description: Allow players to edit contents of the books stored by the plugin.
  bookrules.edit.group:
    default: op
    description: Allow players to edit groups of books.
  bookrules.list:
    default: true
    description: Allow players to list all books stored by the plugin.
  bookrules.setauthor:
    default: op
    description: Allow players to change the author of a written book.
  bookrules.settitle:
    default: op
    description: Allow players to change the title of a written book.
  bookrules.unsign:
    default: op
    description: Allow players to unsign written books, reverting them to a book and quill.